// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl1tjzYzrLDA-qTLXdJPlItm-pW2tVf6I',
    appId: '1:507370237532:web:1ae9227a20997c4c020099',
    messagingSenderId: '507370237532',
    projectId: 'login-project-4db55',
    authDomain: 'login-project-4db55.firebaseapp.com',
    databaseURL: 'https://login-project-4db55-default-rtdb.firebaseio.com',
    storageBucket: 'login-project-4db55.firebasestorage.app',
    measurementId: 'G-4RPHG5VG3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoRKKQlb2IOqXDnfRMupQjoBjaU1JvkBw',
    appId: '1:507370237532:android:283e8dea6648427f020099',
    messagingSenderId: '507370237532',
    projectId: 'login-project-4db55',
    databaseURL: 'https://login-project-4db55-default-rtdb.firebaseio.com',
    storageBucket: 'login-project-4db55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ6WQpE5YDyuGn5RRpW_kl4DXq3k_1WuI',
    appId: '1:507370237532:ios:156edc693273b455020099',
    messagingSenderId: '507370237532',
    projectId: 'login-project-4db55',
    databaseURL: 'https://login-project-4db55-default-rtdb.firebaseio.com',
    storageBucket: 'login-project-4db55.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConnectTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ6WQpE5YDyuGn5RRpW_kl4DXq3k_1WuI',
    appId: '1:507370237532:ios:156edc693273b455020099',
    messagingSenderId: '507370237532',
    projectId: 'login-project-4db55',
    databaseURL: 'https://login-project-4db55-default-rtdb.firebaseio.com',
    storageBucket: 'login-project-4db55.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConnectTest',
  );
}
